"""empty message

Revision ID: 258adad8ba12
Revises: 2bfb62f5b1d3
Create Date: 2021-01-26 15:21:30.847488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258adad8ba12'
down_revision = '2bfb62f5b1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order', 'user', ['user_id'], ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    # ### end Alembic commands ###
