"""empty message

Revision ID: 2bfb62f5b1d3
Revises: 4688e9d95593
Create Date: 2021-01-26 15:21:05.469851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bfb62f5b1d3'
down_revision = '4688e9d95593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_user_id_fkey', 'order', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('order_user_id_fkey', 'order', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
