"""empty message

Revision ID: 82f83b8867c3
Revises: c8a542b90c8a
Create Date: 2021-01-31 08:31:27.005317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f83b8867c3'
down_revision = 'c8a542b90c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_product_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_product_id_fkey', 'order', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
